### ISSUE TITLE
[Bug] GraphRAG Backend application is crashing

### ISSUE THREAD

**Issue by artem-astafev** [opea-project/GenAIComps#1047]
### Priority

P3-Medium

### OS type

Ubuntu

### Hardware type

GPU-AMD

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [X] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

https://github.com/opea-project/GenAIExamples/commit/e18369ba0d7f9ab5ddc35ed6dedcf03899766902, PR https://github.com/opea-project/GenAIExamples/pull/1250/files

### Description

 GraphRAG backend application(MegaService) is crushing with` ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py) ` error

### Reproduce steps

1. fetch GenAIExample git repo - git clone https://github.com/opea-project/GenAIExamples.git
2. go to docker_image_build - cd ./GenAIExamples/GraphRAG/docker_image_build/
3. fetch GenAIComps repo -  git clone https://github.com/opea-project/GenAIComps.git
4. build images with docker compose - docker compose -f build.yaml build
5. run GraphRAG with docker compose 

### Raw log

```shell
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
graphrag-backend-server  | Traceback (most recent call last):
graphrag-backend-server  |   File "/home/user/graphrag.py", line 10, in <module>
graphrag-backend-server  |     from comps.cores.mega.utils import handle_message
graphrag-backend-server  | ImportError: cannot import name 'handle_message' from 'comps.cores.mega.utils' (/home/user/GenAIComps/comps/cores/mega/utils.py)
```

**Comment by artem-astafev** [comment]
Wrong Repo, re-create Issue in GenAIExamples https://github.com/opea-project/GenAIExamples/issues/1276
