### ISSUE TITLE
retriever-redis image can NOT be launched

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIComps#398]
Building the latest (commt id `de27e6b`) retriever-redis image following the [README](https://github.com/opea-project/GenAIComps/blob/main/comps/retrievers/langchain/redis/README.md), then launch with it with docker, will find that image can not be launched at all. The container logs shows the following error:

```
$ sudo docker logs retriever-redis-server
/home/user/.local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:161: UserWarning: Field "model_name_or_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/home/user/.local/lib/python3.11/site-packages/langchain/__init__.py:30: UserWarning: Importing LLMChain from langchain root module is no longer supported. Please use langchain.chains.LLMChain instead.
  warnings.warn(
/home/user/.local/lib/python3.11/site-packages/langchain/__init__.py:30: UserWarning: Importing PromptTemplate from langchain root module is no longer supported. Please use langchain_core.prompts.PromptTemplate instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/comps/dataprep/redis/langchain/prepare_doc_redis.py", line 211, in <module>
    @register_microservice(name="opea_service@prepare_doc_redis", endpoint="/v1/dataprep", host="0.0.0.0", port=6007)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comps/cores/mega/micro_service.py", line 159, in decorator
    micro_service = MicroService(
                    ^^^^^^^^^^^^^
  File "/home/user/comps/cores/mega/micro_service.py", line 59, in __init__
    self.server = self._get_server()
                  ^^^^^^^^^^^^^^^^^^
  File "/home/user/comps/cores/mega/micro_service.py", line 81, in _get_server
    from .http_service import HTTPService
  File "/home/user/comps/cores/mega/http_service.py", line 8, in <module>
    from uvicorn import Config, Server
ModuleNotFoundError: No module named 'uvicorn'

```

**Comment by Feelas** [comment]
Most likely duplicate of https://github.com/opea-project/GenAIComps/pull/397?

**Comment by lianhao** [comment]
> GenAIComps/comps/dataprep/redis/langchain/docker/Dockerfile GenAIComps/comps/retrievers/langchain/redis/docker/Dockerfile
> 
> Which one did you use to build your image?

comps/retrievers/langchain/redis/docker/Dockerfile

**Comment by lianhao** [comment]
> Most likely duplicate of #395?

Seems right, looks like module 'uvicorn' is not installed during docker image build time. I guess this will affect all uservices using mega core

**Comment by lianhao** [comment]
Looks like PR #404  has fixed this issue. Close it now.
