### ISSUE TITLE
[Bug] llm-faqgen-tgi fail to process request

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIComps#969]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-SPR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [X] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

git commit 3328ea3

### Description

Following [llm-faqgen-tgi README](https://github.com/opea-project/GenAIComps/tree/main/comps/llms/faq-generation/tgi/langchain), build the docker image from source, and launch the llm-faqgen-tgi service using docker compose, sending the following curl command to verify and fails:

```
$ curl http://${your_ip}:9000/v1/faqgen \
  -X POST \
  -d '{"query":"Text Embeddings Inference (TEI) is a toolkit for deploying and serving open source text embeddings and sequence classification models. TEI enables high-performance
extraction for the most popular models, including FlagEmbedding, Ember, GTE and E5."}' \
  -H 'Content-Type: application/json'
curl: (18) transfer closed with outstanding read data remaining
```

### Reproduce steps

Follow  [llm-faqgen-tgi README](https://github.com/opea-project/GenAIComps/tree/main/comps/llms/faq-generation/tgi/langchain), do the following steps:

1. Do Step 1.1: set env, with model meta-llama/Meta-Llama-3-8B-Instruct
2. Do Step 1.2: build docker images
3. Do step 1.4: launch services
4. Do step 3.2: consume FAQGen LLM Service  fails

### Raw log

```shell
$ docker compose -f docker_compose_llm.yaml logs llm
WARN[0000] /home/lianhao/GenAIComps/comps/llms/faq-generation/tgi/langchain/docker_compose_llm.yaml: `version` is obsolete
llm-faqgen-server  | Defaulting to user installation because normal site-packages is not writeable
llm-faqgen-server  | Collecting langserve (from -r requirements-runtime.txt (line 1))
llm-faqgen-server  |   Downloading langserve-0.3.0-py3-none-any.whl.metadata (39 kB)
llm-faqgen-server  | Requirement already satisfied: httpx<1.0,>=0.23.0 in /home/user/.local/lib/python3.11/site-packages (from langserve->-r requirements-runtime.txt (line 1)) (0.2
8.0)
... ...
llm-faqgen-server  | Installing collected packages: langserve                                                                                                              [42/1960]
llm-faqgen-server  | Successfully installed langserve-0.3.0
llm-faqgen-server  | [2024-12-04 08:10:20,462] [    INFO] - Base service - CORS is enabled.
llm-faqgen-server  | [2024-12-04 08:10:20,462] [    INFO] - Base service - Setting up HTTP server
llm-faqgen-server  | [2024-12-04 08:10:20,463] [    INFO] - Base service - Uvicorn server setup on port 9000
llm-faqgen-server  | INFO:     Waiting for application startup.
llm-faqgen-server  | INFO:     Application startup complete.
llm-faqgen-server  | INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
llm-faqgen-server  | [2024-12-04 08:10:20,474] [    INFO] - Base service - HTTP server setup successful
llm-faqgen-server  | /home/user/comps/llms/faq-generation/tgi/langchain/llm.py:52: LangChainDeprecationWarning: The class `HuggingFaceEndpoint` was deprecated in LangChain 0.0.37 a
nd will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~l
angchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEndpoint``.
llm-faqgen-server  |   llm = HuggingFaceEndpoint(
llm-faqgen-server  | INFO:     100.83.122.254:54542 - "POST /v1/faqgen HTTP/1.1" 200 OK
llm-faqgen-server  | ERROR:    Exception in ASGI application
llm-faqgen-server  | Traceback (most recent call last):
llm-faqgen-server  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 259, in __call__
llm-faqgen-server  |     await wrap(partial(self.listen_for_disconnect, receive))
llm-faqgen-server  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
llm-faqgen-server  |     await func()
llm-faqgen-server  |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 232, in listen_for_disconnect
llm-faqgen-server  |     message = await receive()
llm-faqgen-server  |               ^^^^^^^^^^^^^^^
llm-faqgen-server  |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 531, in receive
llm-faqgen-server  |     await self.message_event.wait()
llm-faqgen-server  |   File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
llm-faqgen-server  |     await fut
llm-faqgen-server  | asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f446182aed0
llm-faqgen-server  |
llm-faqgen-server  | During handling of the above exception, another exception occurred:
llm-faqgen-server  |
llm-faqgen-server  |   + Exception Group Traceback (most recent call last):
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
llm-faqgen-server  |   |     result = await app(  # type: ignore[func-returns-value]
llm-faqgen-server  |   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
llm-faqgen-server  |   |     return await self.app(scope, receive, send)
llm-faqgen-server  |   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
llm-faqgen-server  |   |     await super().__call__(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
llm-faqgen-server  |   |     await self.middleware_stack(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
llm-faqgen-server  |   |     raise exc
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
llm-faqgen-server  |   |     await self.app(scope, receive, _send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 174, in __call__
llm-faqgen-server  |   |     raise exc
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 172, in __call__
llm-faqgen-server  |   |     await self.app(scope, receive, send_wrapper)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
llm-faqgen-server  |   |     await self.app(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
llm-faqgen-server  |   |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
llm-faqgen-server  |   |     raise exc
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
llm-faqgen-server  |   |     await app(scope, receive, sender)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
llm-faqgen-server  |   |     await self.middleware_stack(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
llm-faqgen-server  |   |     await route.handle(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
llm-faqgen-server  |   |     await self.app(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
llm-faqgen-server  |   |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
llm-faqgen-server  |   |     raise exc
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
llm-faqgen-server  |   |     await app(scope, receive, sender)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
llm-faqgen-server  |   |     await response(scope, receive, send)
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 252, in __call__
llm-faqgen-server  |   |     async with anyio.create_task_group() as task_group:
llm-faqgen-server  |   |   File "/home/user/.local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
llm-faqgen-server  |   |     raise BaseExceptionGroup(
llm-faqgen-server  |   | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
llm-faqgen-server  |   +-+---------------- 1 ----------------
llm-faqgen-server  |     | Traceback (most recent call last):
llm-faqgen-server  |     |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
llm-faqgen-server  |     |     await func()
llm-faqgen-server  |     |   File "/home/user/.local/lib/python3.11/site-packages/starlette/responses.py", line 244, in stream_response
llm-faqgen-server  |     |     async for chunk in self.body_iterator:
llm-faqgen-server  |     |   File "/home/user/comps/llms/faq-generation/tgi/langchain/llm.py", line 77, in stream_generator
llm-faqgen-server  |     |     from langserve.serialization import WellKnownLCSerializer
llm-faqgen-server  |     |   File "/home/user/.local/lib/python3.11/site-packages/langserve/__init__.py", line 8, in <module>
llm-faqgen-server  |     |     from langserve.client import RemoteRunnable
llm-faqgen-server  |     |   File "/home/user/.local/lib/python3.11/site-packages/langserve/client.py", line 24, in <module>
llm-faqgen-server  |     |     from httpx._types import AuthTypes, CertTypes, CookieTypes, HeaderTypes, VerifyTypes
llm-faqgen-server  |     | ImportError: cannot import name 'VerifyTypes' from 'httpx._types' (/home/user/.local/lib/python3.11/site-packages/httpx/_types.py)
llm-faqgen-server  |     +------------------------------------

```

**Comment by lianhao** [comment]
I'm using fastapi==0.115.6.

This seems to be an upstream issue https://github.com/langchain-ai/langserve/issues/796

**Comment by hteeyeoh** [comment]
another workaround is to Downgrade httpx to 0.27.2 as mentioned in https://github.com/langchain-ai/langserve/issues/796

**Comment by lianhao** [comment]
[langserve 0.3.1 is available in pypi](https://pypi.org/project/langserve/#history) to unblock the faqgen CI failure
